FROM postgres:15.8-bookworm

# Config taken from: https://github.com/postgis/docker-postgis/blob/master/15-3.5/Dockerfile
ENV POSTGIS_MAJOR 3

RUN apt-get update \
  && apt-cache showpkg postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
  && apt-get install -y --no-install-recommends --fix-missing \
  postgis \
  postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts \
  && rm -rf /var/lib/apt/lists/*

COPY ./enable-extensions.sh /docker-entrypoint-initdb.d
