--
-- PostgreSQL database dump
--

\restrict FdlCOJctZ0FeTBmzYIduMOCmh7vHAXefXQW1fqJMxH14twrcfTNFUqDakk8jHdS

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 18.1 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: home_type_enum; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.home_type_enum AS ENUM (
    'Apartment',
    'ApartmentUnitFlat',
    'BlockOfUnits',
    'DevelopmentSite',
    'Duplex',
    'FreeStanding',
    'House',
    'Land',
    'NewApartments',
    'NewHomeDesigns',
    'NewHouseLand',
    'NewLand',
    'PentHouse',
    'Retirement',
    'SemiDetached',
    'Studio',
    'Terrace',
    'Townhouse',
    'VacantLand',
    'Villa'
);


ALTER TYPE public.home_type_enum OWNER TO "user";

--
-- Name: state_abbreviation_enum; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.state_abbreviation_enum AS ENUM (
    'ACT',
    'NSW',
    'NT',
    'QLD',
    'SA',
    'TAS',
    'VIC',
    'WA'
);


ALTER TYPE public.state_abbreviation_enum OWNER TO "user";

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: home_feature_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.home_feature_table (
    id integer NOT NULL,
    bed_quantity integer NOT NULL,
    bath_quantity integer NOT NULL,
    car_quantity integer NOT NULL,
    home_type public.home_type_enum NOT NULL,
    is_retirement boolean NOT NULL,
    CONSTRAINT home_feature_table_bath_quantity_check CHECK ((bath_quantity >= 0)),
    CONSTRAINT home_feature_table_bed_quantity_check CHECK ((bed_quantity >= 0)),
    CONSTRAINT home_feature_table_car_quantity_check CHECK ((car_quantity >= 0))
);


ALTER TABLE public.home_feature_table OWNER TO "user";

--
-- Name: home_feature_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.home_feature_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_feature_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: home_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.home_table (
    id integer NOT NULL,
    locality_table_id integer NOT NULL,
    home_feature_table_id integer NOT NULL,
    street_address text NOT NULL,
    gps public.geometry(Point),
    land_m2 integer NOT NULL,
    inspection_time timestamp with time zone,
    auction_time timestamp with time zone,
    CONSTRAINT home_table_land_m2_check CHECK ((land_m2 >= 0)),
    CONSTRAINT home_table_street_address_check CHECK (((length(street_address) > 0) AND (length(street_address) < 64)))
);


ALTER TABLE public.home_table OWNER TO "user";

--
-- Name: home_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.home_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kysely_migration; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.kysely_migration (
    name character varying(255) NOT NULL,
    "timestamp" character varying(255) NOT NULL
);


ALTER TABLE public.kysely_migration OWNER TO "user";

--
-- Name: kysely_migration_lock; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.kysely_migration_lock (
    id character varying(255) NOT NULL,
    is_locked integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.kysely_migration_lock OWNER TO "user";

--
-- Name: rent_price_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.rent_price_table (
    id integer NOT NULL,
    home_table_id integer NOT NULL,
    first_scrape_date date DEFAULT now() NOT NULL,
    last_scrape_date date DEFAULT now() NOT NULL,
    weekly_rent_aud real NOT NULL,
    aud_per_bed real NOT NULL,
    aud_per_land_m2 real NOT NULL
);


ALTER TABLE public.rent_price_table OWNER TO "user";

--
-- Name: latest_rent_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: user
--

CREATE MATERIALIZED VIEW public.latest_rent_mv AS
 WITH scrape_dates AS (
         SELECT rent_price_table.last_scrape_date,
            count(*) AS frequency
           FROM public.rent_price_table
          WHERE (rent_price_table.last_scrape_date > (now() - '4 days'::interval))
          GROUP BY rent_price_table.last_scrape_date
          ORDER BY (count(*)) DESC
         LIMIT 2
        ), latest_rent_price AS (
         SELECT DISTINCT ON (rent_price_table.home_table_id) rent_price_table.id,
            rent_price_table.home_table_id,
            rent_price_table.first_scrape_date,
            rent_price_table.last_scrape_date,
            rent_price_table.weekly_rent_aud,
            rent_price_table.aud_per_bed,
            rent_price_table.aud_per_land_m2
           FROM public.rent_price_table
          WHERE (rent_price_table.last_scrape_date >= ( SELECT max(scrape_dates.last_scrape_date) AS max
                   FROM scrape_dates))
          ORDER BY rent_price_table.home_table_id, rent_price_table.last_scrape_date DESC
        )
 SELECT latest_rent_price.first_scrape_date,
    latest_rent_price.last_scrape_date,
    latest_rent_price.weekly_rent_aud,
    latest_rent_price.aud_per_bed,
    latest_rent_price.aud_per_land_m2,
    home_table.auction_time,
    public.st_x(home_table.gps) AS longitude,
    public.st_y(home_table.gps) AS latitude,
    home_table.inspection_time,
    home_table.land_m2,
    home_table.locality_table_id,
    home_table.street_address,
    home_feature_table.bed_quantity,
    home_feature_table.bath_quantity,
    home_feature_table.car_quantity,
    home_feature_table.home_type,
    home_feature_table.is_retirement
   FROM ((latest_rent_price
     LEFT JOIN public.home_table ON ((latest_rent_price.home_table_id = home_table.id)))
     LEFT JOIN public.home_feature_table ON ((home_table.home_feature_table_id = home_feature_table.id)))
  WITH NO DATA;


ALTER MATERIALIZED VIEW public.latest_rent_mv OWNER TO "user";

--
-- Name: locality_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.locality_table (
    id integer NOT NULL,
    suburb_name text NOT NULL,
    postcode text NOT NULL,
    state_abbreviation public.state_abbreviation_enum NOT NULL,
    boundary_coordinates public.geometry(Polygon) NOT NULL,
    CONSTRAINT locality_table_postcode_check CHECK ((length(postcode) = 4)),
    CONSTRAINT locality_table_suburb_name_check CHECK (((length(suburb_name) > 0) AND (length(suburb_name) < 64)))
);


ALTER TABLE public.locality_table OWNER TO "user";

--
-- Name: latest_rent_view; Type: VIEW; Schema: public; Owner: user
--

CREATE VIEW public.latest_rent_view AS
 SELECT rent_price_table.first_scrape_date,
    rent_price_table.last_scrape_date,
    rent_price_table.weekly_rent_aud,
    rent_price_table.aud_per_bed,
    rent_price_table.aud_per_land_m2,
    rent_price_table.home_table_id,
    home_table.street_address,
    home_table.gps,
    home_table.land_m2,
    home_table.inspection_time,
    home_table.auction_time,
    home_table.home_feature_table_id,
    home_feature_table.bed_quantity,
    home_feature_table.bath_quantity,
    home_feature_table.car_quantity,
    home_feature_table.home_type,
    home_feature_table.is_retirement,
    home_table.locality_table_id,
    locality_table.suburb_name,
    locality_table.state_abbreviation,
    locality_table.postcode,
    locality_table.boundary_coordinates
   FROM (((public.rent_price_table
     LEFT JOIN public.home_table ON ((rent_price_table.home_table_id = home_table.id)))
     LEFT JOIN public.home_feature_table ON ((home_table.home_feature_table_id = home_feature_table.id)))
     LEFT JOIN public.locality_table ON ((home_table.locality_table_id = locality_table.id)))
  WHERE (rent_price_table.last_scrape_date = ( SELECT max(rent_price_table_1.last_scrape_date) AS max
           FROM public.rent_price_table rent_price_table_1));


ALTER VIEW public.latest_rent_view OWNER TO "user";

--
-- Name: sale_price_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.sale_price_table (
    id integer NOT NULL,
    home_table_id integer NOT NULL,
    first_scrape_date date DEFAULT now() NOT NULL,
    last_scrape_date date DEFAULT now() NOT NULL,
    higher_price_aud integer NOT NULL,
    aud_per_bed real NOT NULL,
    aud_per_land_m2 real NOT NULL
);


ALTER TABLE public.sale_price_table OWNER TO "user";

--
-- Name: latest_sale_mv; Type: MATERIALIZED VIEW; Schema: public; Owner: user
--

CREATE MATERIALIZED VIEW public.latest_sale_mv AS
 WITH scrape_dates AS (
         SELECT sale_price_table.last_scrape_date,
            count(*) AS frequency
           FROM public.sale_price_table
          WHERE (sale_price_table.last_scrape_date > (now() - '4 days'::interval))
          GROUP BY sale_price_table.last_scrape_date
          ORDER BY (count(*)) DESC
         LIMIT 2
        ), latest_sale_price AS (
         SELECT DISTINCT ON (sale_price_table.home_table_id) sale_price_table.id,
            sale_price_table.home_table_id,
            sale_price_table.first_scrape_date,
            sale_price_table.last_scrape_date,
            sale_price_table.higher_price_aud,
            sale_price_table.aud_per_bed,
            sale_price_table.aud_per_land_m2
           FROM public.sale_price_table
          WHERE (sale_price_table.last_scrape_date >= ( SELECT max(scrape_dates.last_scrape_date) AS max
                   FROM scrape_dates))
          ORDER BY sale_price_table.home_table_id, sale_price_table.last_scrape_date DESC
        )
 SELECT latest_sale_price.first_scrape_date,
    latest_sale_price.last_scrape_date,
    latest_sale_price.higher_price_aud,
    latest_sale_price.aud_per_bed,
    latest_sale_price.aud_per_land_m2,
    home_table.auction_time,
    public.st_x(home_table.gps) AS longitude,
    public.st_y(home_table.gps) AS latitude,
    home_table.inspection_time,
    home_table.land_m2,
    home_table.locality_table_id,
    home_table.street_address,
    home_feature_table.bed_quantity,
    home_feature_table.bath_quantity,
    home_feature_table.car_quantity,
    home_feature_table.home_type,
    home_feature_table.is_retirement
   FROM ((latest_sale_price
     LEFT JOIN public.home_table ON ((latest_sale_price.home_table_id = home_table.id)))
     LEFT JOIN public.home_feature_table ON ((home_table.home_feature_table_id = home_feature_table.id)))
  WITH NO DATA;


ALTER MATERIALIZED VIEW public.latest_sale_mv OWNER TO "user";

--
-- Name: latest_sale_view; Type: VIEW; Schema: public; Owner: user
--

CREATE VIEW public.latest_sale_view AS
 SELECT sale_price_table.first_scrape_date,
    sale_price_table.last_scrape_date,
    sale_price_table.higher_price_aud,
    sale_price_table.aud_per_bed,
    sale_price_table.aud_per_land_m2,
    sale_price_table.home_table_id,
    home_table.street_address,
    home_table.gps,
    home_table.land_m2,
    home_table.inspection_time,
    home_table.auction_time,
    home_table.home_feature_table_id,
    home_feature_table.bed_quantity,
    home_feature_table.bath_quantity,
    home_feature_table.car_quantity,
    home_feature_table.home_type,
    home_feature_table.is_retirement,
    home_table.locality_table_id,
    locality_table.suburb_name,
    locality_table.state_abbreviation,
    locality_table.postcode,
    locality_table.boundary_coordinates
   FROM (((public.sale_price_table
     LEFT JOIN public.home_table ON ((sale_price_table.home_table_id = home_table.id)))
     LEFT JOIN public.home_feature_table ON ((home_table.home_feature_table_id = home_feature_table.id)))
     LEFT JOIN public.locality_table ON ((home_table.locality_table_id = locality_table.id)))
  WHERE (sale_price_table.last_scrape_date = ( SELECT max(sale_price_table_1.last_scrape_date) AS max
           FROM public.sale_price_table sale_price_table_1));


ALTER VIEW public.latest_sale_view OWNER TO "user";

--
-- Name: locality_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.locality_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locality_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rent_price_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.rent_price_table ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rent_price_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_price_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.sale_price_table ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sale_price_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_feature_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.school_feature_table (
    id integer NOT NULL,
    "primary" boolean NOT NULL,
    secondary boolean NOT NULL,
    government_sector boolean NOT NULL,
    independent boolean NOT NULL,
    special_needs boolean NOT NULL
);


ALTER TABLE public.school_feature_table OWNER TO "user";

--
-- Name: school_feature_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.school_feature_table ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.school_feature_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.school_table (
    id integer NOT NULL,
    locality_table_id integer NOT NULL,
    school_feature_table_id integer NOT NULL,
    acara_id integer NOT NULL,
    name text NOT NULL,
    url text,
    gps public.geometry(Point) NOT NULL
);


ALTER TABLE public.school_table OWNER TO "user";

--
-- Name: school_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.school_table ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.school_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_view; Type: VIEW; Schema: public; Owner: user
--

CREATE VIEW public.school_view AS
 SELECT school_table.acara_id,
    school_table.name,
    school_table.url,
    school_table.gps,
    school_table.school_feature_table_id,
    school_feature_table."primary",
    school_feature_table.secondary,
    school_feature_table.government_sector,
    school_feature_table.independent,
    school_feature_table.special_needs,
    school_table.locality_table_id,
    locality_table.suburb_name,
    locality_table.state_abbreviation,
    locality_table.postcode,
    locality_table.boundary_coordinates
   FROM ((public.school_table
     LEFT JOIN public.school_feature_table ON ((school_table.school_feature_table_id = school_feature_table.id)))
     LEFT JOIN public.locality_table ON ((school_table.locality_table_id = locality_table.id)));


ALTER VIEW public.school_view OWNER TO "user";

--
-- Data for Name: home_feature_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.home_feature_table (id, bed_quantity, bath_quantity, car_quantity, home_type, is_retirement) FROM stdin;
\.


--
-- Data for Name: home_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.home_table (id, locality_table_id, home_feature_table_id, street_address, gps, land_m2, inspection_time, auction_time) FROM stdin;
\.


--
-- Data for Name: kysely_migration; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.kysely_migration (name, "timestamp") FROM stdin;
V0001__enable-postgis	2026-01-06T11:39:34.412Z
V0002__add-home_feature_table	2026-01-06T11:39:34.424Z
V0003__add-locality_table	2026-01-06T11:39:34.426Z
V0004__add-home_table	2026-01-06T11:39:34.428Z
V0005__add-sale_price_table	2026-01-06T11:39:34.430Z
V0006__add-rent_price_table	2026-01-06T11:39:34.431Z
V0007__add-school_feature_table	2026-01-06T11:39:34.432Z
V0008__add-school_table	2026-01-06T11:39:34.435Z
V0009__alter-home_table-alter-gps_column	2026-01-06T11:39:34.436Z
V0010__add-indexes_to_foreign_keys	2026-01-06T11:39:34.439Z
V0011__add-latest_sale_view	2026-01-06T11:39:34.443Z
V0012__add-latest_rent_view	2026-01-06T11:39:34.446Z
V0013__add-school_view	2026-01-06T11:39:34.447Z
V0014__alter-latest_sale_mv	2026-01-06T11:39:34.451Z
V0015__alter-rent_price_mv	2026-01-06T11:39:34.454Z
\.


--
-- Data for Name: kysely_migration_lock; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.kysely_migration_lock (id, is_locked) FROM stdin;
migration_lock	0
\.


--
-- Data for Name: locality_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.locality_table (id, suburb_name, postcode, state_abbreviation, boundary_coordinates) FROM stdin;
\.


--
-- Data for Name: rent_price_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.rent_price_table (id, home_table_id, first_scrape_date, last_scrape_date, weekly_rent_aud, aud_per_bed, aud_per_land_m2) FROM stdin;
\.


--
-- Data for Name: sale_price_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.sale_price_table (id, home_table_id, first_scrape_date, last_scrape_date, higher_price_aud, aud_per_bed, aud_per_land_m2) FROM stdin;
\.


--
-- Data for Name: school_feature_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.school_feature_table (id, "primary", secondary, government_sector, independent, special_needs) FROM stdin;
\.


--
-- Data for Name: school_table; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.school_table (id, locality_table_id, school_feature_table_id, acara_id, name, url, gps) FROM stdin;
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Name: home_feature_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.home_feature_table_id_seq', 1, false);


--
-- Name: home_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.home_table_id_seq', 1, false);


--
-- Name: locality_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.locality_table_id_seq', 1, false);


--
-- Name: rent_price_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.rent_price_table_id_seq', 1, false);


--
-- Name: sale_price_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.sale_price_table_id_seq', 1, false);


--
-- Name: school_feature_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.school_feature_table_id_seq', 1, false);


--
-- Name: school_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.school_table_id_seq', 1, false);


--
-- Name: home_feature_table home_feature_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_feature_table
    ADD CONSTRAINT home_feature_table_pkey PRIMARY KEY (id);


--
-- Name: home_feature_table home_feature_table_unique; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_feature_table
    ADD CONSTRAINT home_feature_table_unique UNIQUE (bed_quantity, bath_quantity, car_quantity, home_type, is_retirement);


--
-- Name: home_table home_table_locality_table_id_street_address_unique; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_locality_table_id_street_address_unique UNIQUE (locality_table_id, street_address);


--
-- Name: home_table home_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_pkey PRIMARY KEY (id);


--
-- Name: kysely_migration_lock kysely_migration_lock_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.kysely_migration_lock
    ADD CONSTRAINT kysely_migration_lock_pkey PRIMARY KEY (id);


--
-- Name: kysely_migration kysely_migration_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.kysely_migration
    ADD CONSTRAINT kysely_migration_pkey PRIMARY KEY (name);


--
-- Name: locality_table locality_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.locality_table
    ADD CONSTRAINT locality_table_pkey PRIMARY KEY (id);


--
-- Name: locality_table locality_table_suburb_name_postcode_state_abbreviation_unique; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.locality_table
    ADD CONSTRAINT locality_table_suburb_name_postcode_state_abbreviation_unique UNIQUE (suburb_name, postcode, state_abbreviation);


--
-- Name: rent_price_table rent_price_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.rent_price_table
    ADD CONSTRAINT rent_price_table_pkey PRIMARY KEY (id);


--
-- Name: sale_price_table sale_price_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sale_price_table
    ADD CONSTRAINT sale_price_table_pkey PRIMARY KEY (id);


--
-- Name: school_feature_table school_feature_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_feature_table
    ADD CONSTRAINT school_feature_table_pkey PRIMARY KEY (id);


--
-- Name: school_feature_table school_feature_table_unique; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_feature_table
    ADD CONSTRAINT school_feature_table_unique UNIQUE ("primary", secondary, government_sector, independent, special_needs);


--
-- Name: school_table school_table_acara_id_unique; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_table
    ADD CONSTRAINT school_table_acara_id_unique UNIQUE (acara_id);


--
-- Name: school_table school_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_table
    ADD CONSTRAINT school_table_pkey PRIMARY KEY (id);


--
-- Name: home_table_home_feature_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX home_table_home_feature_table_id_idx ON public.home_table USING btree (home_feature_table_id);


--
-- Name: home_table_locality_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX home_table_locality_table_id_idx ON public.home_table USING btree (locality_table_id);


--
-- Name: rent_price_table_home_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX rent_price_table_home_table_id_idx ON public.rent_price_table USING btree (home_table_id);


--
-- Name: rent_price_table_last_scrape_date_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX rent_price_table_last_scrape_date_idx ON public.rent_price_table USING btree (last_scrape_date);


--
-- Name: sale_price_table_home_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX sale_price_table_home_table_id_idx ON public.sale_price_table USING btree (home_table_id);


--
-- Name: sale_price_table_last_scrape_date_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX sale_price_table_last_scrape_date_idx ON public.sale_price_table USING btree (last_scrape_date);


--
-- Name: school_table_locality_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX school_table_locality_table_id_idx ON public.school_table USING btree (locality_table_id);


--
-- Name: school_table_school_feature_table_id_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX school_table_school_feature_table_id_idx ON public.school_table USING btree (school_feature_table_id);


--
-- Name: home_table home_table_home_feature_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_home_feature_table_id_fkey FOREIGN KEY (home_feature_table_id) REFERENCES public.home_feature_table(id);


--
-- Name: home_table home_table_locality_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_locality_table_id_fkey FOREIGN KEY (locality_table_id) REFERENCES public.locality_table(id);


--
-- Name: rent_price_table rent_price_table_home_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.rent_price_table
    ADD CONSTRAINT rent_price_table_home_table_id_fkey FOREIGN KEY (home_table_id) REFERENCES public.home_table(id);


--
-- Name: sale_price_table sale_price_table_home_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sale_price_table
    ADD CONSTRAINT sale_price_table_home_table_id_fkey FOREIGN KEY (home_table_id) REFERENCES public.home_table(id);


--
-- Name: school_table school_table_locality_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_table
    ADD CONSTRAINT school_table_locality_table_id_fkey FOREIGN KEY (locality_table_id) REFERENCES public.locality_table(id);


--
-- Name: school_table school_table_school_feature_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.school_table
    ADD CONSTRAINT school_table_school_feature_table_id_fkey FOREIGN KEY (school_feature_table_id) REFERENCES public.school_feature_table(id);


--
-- Name: latest_rent_mv; Type: MATERIALIZED VIEW DATA; Schema: public; Owner: user
--

REFRESH MATERIALIZED VIEW public.latest_rent_mv;


--
-- Name: latest_sale_mv; Type: MATERIALIZED VIEW DATA; Schema: public; Owner: user
--

REFRESH MATERIALIZED VIEW public.latest_sale_mv;


--
-- PostgreSQL database dump complete
--

\unrestrict FdlCOJctZ0FeTBmzYIduMOCmh7vHAXefXQW1fqJMxH14twrcfTNFUqDakk8jHdS

