/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type HomeTypeEnum = 'ApartmentUnitFlat' | 'BlockOfUnits' | 'House' | 'Townhouse'

export type StateAbbreviationEnum = 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface CommonFeaturesTable {
    bath_quantity: number
    bed_quantity: number
    car_quantity: number
    home_type: HomeTypeEnum
    id: Generated<number>
    is_retirement: boolean
}

export interface HomeTable {
    auction_time: Timestamp | null
    common_features_table_id: number | null
    gps: string
    id: Generated<number>
    inspection_time: Timestamp | null
    land_m2: number | null
    localities_table_id: number | null
    street_address: string
}

export interface LocalitiesTable {
    id: Generated<number>
    postcode: string
    state_abbreviation: StateAbbreviationEnum
    suburb_name: string
}

export interface RentPriceTable {
    aud_per_bed: number | null
    aud_per_land_m2: number | null
    first_scrape_date: Generated<string>
    home_table_id: number | null
    id: Generated<number>
    last_scrape_date: Generated<string>
    weekly_rent_aud: number
}

export interface SalePriceTable {
    aud_per_bed: number | null
    aud_per_land_m2: number | null
    first_scrape_date: Generated<string>
    higher_price_aud: number
    home_table_id: number | null
    id: Generated<number>
    last_scrape_date: Generated<string>
}

export interface DB {
    common_features_table: CommonFeaturesTable
    home_table: HomeTable
    localities_table: LocalitiesTable
    rent_price_table: RentPriceTable
    sale_price_table: SalePriceTable
}
