/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type HomeTypeEnum =
    | 'Apartment'
    | 'ApartmentUnitFlat'
    | 'BlockOfUnits'
    | 'DevelopmentSite'
    | 'Duplex'
    | 'FreeStanding'
    | 'House'
    | 'Land'
    | 'NewApartments'
    | 'NewHomeDesigns'
    | 'NewHouseLand'
    | 'NewLand'
    | 'PentHouse'
    | 'Retirement'
    | 'SemiDetached'
    | 'Studio'
    | 'Terrace'
    | 'Townhouse'
    | 'VacantLand'
    | 'Villa'

export type StateAbbreviationEnum = 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface HomeFeatureTable {
    bath_quantity: number
    bed_quantity: number
    car_quantity: number
    home_type: HomeTypeEnum
    id: Generated<number>
    is_retirement: boolean
}

export interface HomeTable {
    auction_time: Timestamp
    gps: string
    home_feature_table_id: number
    id: Generated<number>
    inspection_time: Timestamp
    land_m2: number
    locality_table_id: number
    street_address: string
}

export interface LocalityTable {
    boundary_coordinates: string
    id: Generated<number>
    postcode: string
    state_abbreviation: StateAbbreviationEnum
    suburb_name: string
}

export interface RentPriceTable {
    aud_per_bed: number
    aud_per_land_m2: number
    first_scrape_date: Generated<Timestamp>
    home_table_id: number
    id: Generated<number>
    last_scrape_date: Generated<Timestamp>
    weekly_rent_aud: number
}

export interface SalePriceTable {
    aud_per_bed: number
    aud_per_land_m2: number
    first_scrape_date: Generated<Timestamp>
    higher_price_aud: number
    home_table_id: number
    id: Generated<number>
    last_scrape_date: Generated<Timestamp>
}

export interface SchoolFeatureTable {
    government_sector: boolean
    id: Generated<number>
    independent: boolean
    primary: boolean
    secondary: boolean
    special_needs: boolean
}

export interface SchoolTable {
    acara_id: number
    gps: string
    id: Generated<number>
    locality_table_id: number
    name: string
    school_feature_table_id: number
    url: string
}

export interface DB {
    home_feature_table: HomeFeatureTable
    home_table: HomeTable
    locality_table: LocalityTable
    rent_price_table: RentPriceTable
    sale_price_table: SalePriceTable
    school_feature_table: SchoolFeatureTable
    school_table: SchoolTable
}
