// Generated by ts-to-zod
import { z } from 'zod'

export const homeTypeEnumSchema = z.enum([
    'Apartment',
    'ApartmentUnitFlat',
    'BlockOfUnits',
    'DevelopmentSite',
    'Duplex',
    'FreeStanding',
    'House',
    'Land',
    'NewApartments',
    'NewHomeDesigns',
    'NewHouseLand',
    'NewLand',
    'PentHouse',
    'Retirement',
    'SemiDetached',
    'Studio',
    'Terrace',
    'Townhouse',
    'VacantLand',
    'Villa',
])

export const stateAbbreviationEnumSchema = z.enum([
    'ACT',
    'NSW',
    'NT',
    'QLD',
    'SA',
    'TAS',
    'VIC',
    'WA',
])

export const timestampSchema = z.coerce.date()

export const homeFeatureTableSchema = z.object({
    bath_quantity: z.number(),
    bed_quantity: z.number(),
    car_quantity: z.number(),
    home_type: homeTypeEnumSchema,
    id: z.number(),
    is_retirement: z.boolean(),
})

export const homeTableSchema = z.object({
    auction_time: timestampSchema.nullable(),
    gps: z.string().nullable(),
    home_feature_table_id: z.number(),
    id: z.number(),
    inspection_time: timestampSchema.nullable(),
    land_m2: z.number(),
    locality_table_id: z.number(),
    street_address: z.string(),
})

export const localityTableSchema = z.object({
    boundary_coordinates: z.string(),
    id: z.number(),
    postcode: z.string().length(4),
    state_abbreviation: stateAbbreviationEnumSchema,
    suburb_name: z.string(),
})

export const rentPriceTableSchema = z.object({
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
    first_scrape_date: timestampSchema,
    home_table_id: z.number(),
    id: z.number(),
    last_scrape_date: timestampSchema,
    weekly_rent_aud: z.number(),
})

export const salePriceTableSchema = z.object({
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
    first_scrape_date: timestampSchema,
    higher_price_aud: z.number(),
    home_table_id: z.number(),
    id: z.number(),
    last_scrape_date: timestampSchema,
})

export const schoolFeatureTableSchema = z.object({
    government_sector: z.boolean(),
    id: z.number(),
    independent: z.boolean(),
    primary: z.boolean(),
    secondary: z.boolean(),
    special_needs: z.boolean(),
})

export const schoolTableSchema = z.object({
    acara_id: z.number(),
    gps: z.string(),
    id: z.number(),
    locality_table_id: z.number(),
    name: z.string(),
    school_feature_table_id: z.number(),
    url: z.string().nullable(),
})

export const latestSaleViewSchema = z.object({
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
    first_scrape_date: timestampSchema,
    higher_price_aud: z.number(),
    home_table_id: z.number(),
    last_scrape_date: timestampSchema,
    auction_time: timestampSchema.nullable(),
    gps: z.string().nullable(),
    home_feature_table_id: z.number(),
    inspection_time: timestampSchema.nullable(),
    land_m2: z.number(),
    locality_table_id: z.number(),
    street_address: z.string(),
    bath_quantity: z.number(),
    bed_quantity: z.number(),
    car_quantity: z.number(),
    home_type: homeTypeEnumSchema,
    is_retirement: z.boolean(),
    boundary_coordinates: z.string(),
    postcode: z.string(),
    state_abbreviation: stateAbbreviationEnumSchema,
    suburb_name: z.string(),
})

export const latestRentViewSchema = z.object({
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
    first_scrape_date: timestampSchema,
    weekly_rent_aud: z.number(),
    home_table_id: z.number(),
    last_scrape_date: timestampSchema,
    auction_time: timestampSchema.nullable(),
    gps: z.string().nullable(),
    home_feature_table_id: z.number(),
    inspection_time: timestampSchema.nullable(),
    land_m2: z.number(),
    locality_table_id: z.number(),
    street_address: z.string(),
    bath_quantity: z.number(),
    bed_quantity: z.number(),
    car_quantity: z.number(),
    home_type: homeTypeEnumSchema,
    is_retirement: z.boolean(),
    boundary_coordinates: z.string(),
    postcode: z.string(),
    state_abbreviation: stateAbbreviationEnumSchema,
    suburb_name: z.string(),
})

export const schoolViewSchema = z.object({
    acara_id: z.number(),
    gps: z.string(),
    locality_table_id: z.number(),
    name: z.string(),
    school_feature_table_id: z.number(),
    url: z.string().nullable(),
    government_sector: z.boolean(),
    independent: z.boolean(),
    primary: z.boolean(),
    secondary: z.boolean(),
    special_needs: z.boolean(),
    boundary_coordinates: z.string(),
    postcode: z.string(),
    state_abbreviation: stateAbbreviationEnumSchema,
    suburb_name: z.string(),
})
