/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export enum HomeTypeEnum {
    APARTMENT = 'Apartment',
    APARTMENT_UNIT_FLAT = 'ApartmentUnitFlat',
    BLOCK_OF_UNITS = 'BlockOfUnits',
    DEVELOPMENT_SITE = 'DevelopmentSite',
    DUPLEX = 'Duplex',
    FREE_STANDING = 'FreeStanding',
    HOUSE = 'House',
    LAND = 'Land',
    NEW_APARTMENTS = 'NewApartments',
    NEW_HOME_DESIGNS = 'NewHomeDesigns',
    NEW_HOUSE_LAND = 'NewHouseLand',
    NEW_LAND = 'NewLand',
    PENT_HOUSE = 'PentHouse',
    RETIREMENT = 'Retirement',
    SEMI_DETACHED = 'SemiDetached',
    STUDIO = 'Studio',
    TERRACE = 'Terrace',
    TOWN_HOUSE = 'TownHouse',
    VACANT_LAND = 'VacantLand',
    VILLA = 'Villa',
}

export enum StateAbbreviationEnum {
    ACT = 'ACT',
    NSW = 'NSW',
    NT = 'NT',
    QLD = 'QLD',
    SA = 'SA',
    TAS = 'TAS',
    VIC = 'VIC',
    WA = 'WA',
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface CommonFeaturesTable {
    bath_quantity: number
    bed_quantity: number
    car_quantity: number
    home_type: HomeTypeEnum
    id: Generated<number>
    is_retirement: boolean
}

export interface HomeTable {
    auction_time: Timestamp | null
    common_features_table_id: number
    gps: string
    id: Generated<number>
    inspection_time: Timestamp | null
    land_m2: number
    localities_table_id: number
    street_address: string
}

export interface LocalitiesTable {
    boundary_coordinates: string
    id: Generated<number>
    postcode: string
    state_abbreviation: StateAbbreviationEnum
    suburb_name: string
}

export interface RentPriceTable {
    aud_per_bed: number
    aud_per_land_m2: number
    first_scrape_date: Generated<Timestamp>
    home_table_id: number
    id: Generated<number>
    last_scrape_date: Generated<Timestamp>
    weekly_rent_aud: number
}

export interface SalePriceTable {
    aud_per_bed: number
    aud_per_land_m2: number
    first_scrape_date: Generated<Timestamp>
    higher_price_aud: number
    home_table_id: number
    id: Generated<number>
    last_scrape_date: Generated<Timestamp>
}

export interface DB {
    common_features_table: CommonFeaturesTable
    home_table: HomeTable
    localities_table: LocalitiesTable
    rent_price_table: RentPriceTable
    sale_price_table: SalePriceTable
}
