name: "Setup CI"
description: "Prepare CI job. Setup Nx, node and pnpm. Install dependencies and build affected packages"
inputs:
  job-name:
    required: true
    description: "Name of job - for caching purposes"
outputs:
  nx-cache-key:
    description: "Key for saving Nx tasks cache"
    value: ${{ steps.nx-cache-restore.outputs.cache-primary-key }}
runs:
  using: "composite"
  steps:
    - name: Nx select BASE + HEAD SHAs
      id: setSHAs
      uses: nrwl/nx-set-shas@v4

    - name: Output Nx select BASE + HEAD SHAs
      shell: bash
      run: |
        echo "BASE: ${{ steps.setSHAs.outputs.base }}"
        echo "HEAD: ${{ steps.setSHAs.outputs.head }}"

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        # Reduce installation time with cache - https://github.com/pnpm/action-setup/tree/v4/?tab=readme-ov-file#use-cache-to-reduce-installation-time
        run_install: false

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm i --no-frozen-lockfile

    - name: Build all packages
      shell: bash
      run: pnpm -r build

    - name: Load cache Nx tasks from BASE SHA
      id: nx-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: .nx
        key: nx-cache-${{ inputs.job-name }}-${{ steps.setSHAs.outputs.base }}
