CREATE TYPE "public"."home_type_enum" AS ENUM('ApartmentUnitFlat', 'House', 'Townhouse', 'BlockOfUnits');

CREATE TABLE "common_features_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	"bed_quantity" integer NOT NULL,
	CONSTRAINT "common_features_table_bed_quantity_check" CHECK ("common_features_table"."bed_quantity" >= 0 AND "common_features_table"."bed_quantity" <= 5),
	"bath_quantity" integer NOT NULL,
	CONSTRAINT "common_features_table_bath_quantity_check" CHECK ("common_features_table"."bath_quantity" >= 0  AND "common_features_table"."bath_quantity" <= 5),
	"car_quantity" integer NOT NULL,
	CONSTRAINT "common_features_table_car_quantity_check" CHECK ("common_features_table"."car_quantity" >= 0  AND "common_features_table"."car_quantity" <= 5),
	"home_type" "home_type_enum" NOT NULL,
	"is_retirement" boolean NOT NULL
);
