CREATE TABLE "home_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	"localities_table_id" integer,
  CONSTRAINT "home_table_localities_table_id_localities_table_id_fk" FOREIGN KEY ("localities_table_id") REFERENCES "public"."localities_table"("id"),
	"common_features_table_id" integer,
  CONSTRAINT "home_table_common_features_table_id_common_features_table_id_fk" FOREIGN KEY ("common_features_table_id") REFERENCES "public"."common_features_table"("id"),

	"street_address" text NOT NULL,
	CONSTRAINT "home_table_street_address_check" CHECK (LENGTH("home_table"."street_address") < 64),
	"gps" geometry(point) NOT NULL,
	"land_m2" integer,
	"inspection_time" time,
	"auction_time" time
);
