CREATE TABLE "sale_price_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	"home_table_id" integer,
  CONSTRAINT "sale_price_table_home_table_id_home_table_id_fk" FOREIGN KEY ("home_table_id") REFERENCES "public"."home_table"("id"),

	"first_scrape_date" date DEFAULT now() NOT NULL,
	"last_scrape_date" date DEFAULT now() NOT NULL,
	"higher_price_aud" integer NOT NULL,
	"aud_per_bed" real,
	"aud_per_land_m2" real
);
