CREATE TYPE "public"."state_abbreviation_enum" AS ENUM('ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA');

CREATE TABLE "localities_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

	"suburb_name" text NOT NULL,
	CONSTRAINT "localities_table_suburb_name_check" CHECK (LENGTH("localities_table"."suburb_name") < 64),
	"postcode" text NOT NULL,
	CONSTRAINT "localities_table_postcode_check" CHECK (LENGTH("localities_table"."postcode") = 4),
	"state_abbreviation" "state_abbreviation_enum" NOT NULL
);
