CREATE
    TABLE
        "sale_price_table"(
            "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "home_table_id" INTEGER,
            CONSTRAINT "sale_price_table_home_table_id_home_table_id_fk" FOREIGN KEY("home_table_id") REFERENCES "public"."home_table"("id"),
            "first_scrape_date" DATE DEFAULT now() NOT NULL,
            "last_scrape_date" DATE DEFAULT now() NOT NULL,
            "higher_price_aud" INTEGER NOT NULL,
            "aud_per_bed" REAL,
            "aud_per_land_m2" REAL
        );
