{
 "title": "function-scrape_locality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "heatmap_interval",
    "query": "1s,2s,5s,10s,20s,30s,1m,2m,5m,10m,15m,20m"
   },
   {
    "name": "log_level",
    "query": "fatal,error,warn,info,debug,trace"
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "detected_level heatmap",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "Source",
     "type": "resample",
     "upsampler": "fillna",
     "window": "$heatmap_interval"
    }
   ]
  },
  {
   "title": "code_function_name heatmap",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "Source",
     "type": "resample",
     "upsampler": "fillna",
     "window": "$heatmap_interval"
    }
   ]
  },
  {
   "title": "detected_level exception logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"NewHomie\", service_name=\"function-scrape_locality\"} | detected_level =~ `${log_level}`"
    }
   ]
  }
 ]
}