/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/service-scrape/freemium/latestSale': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['findLatestSale']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/service-scrape/freemium/latestRent': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['findLatestRent']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    findLatestSale: {
        parameters: {
            query?: {
                suburb_name?: string
                state_abbreviation?: 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'
                postcode?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        first_scrape_date: string | null
                        last_scrape_date: string | null
                        higher_price_aud: number | null
                        aud_per_bed: number | null
                        aud_per_land_m2: number | null
                        auction_time: string | null
                        longitude: number | null
                        latitude: number | null
                        inspection_time: string | null
                        land_m2: number | null
                        locality_table_id: number | null
                        street_address: string | null
                        bed_quantity: number | null
                        bath_quantity: number | null
                        car_quantity: number | null
                        home_type:
                            | (
                                  | 'Apartment'
                                  | 'ApartmentUnitFlat'
                                  | 'BlockOfUnits'
                                  | 'DevelopmentSite'
                                  | 'Duplex'
                                  | 'FreeStanding'
                                  | 'House'
                                  | 'Land'
                                  | 'NewApartments'
                                  | 'NewHomeDesigns'
                                  | 'NewHouseLand'
                                  | 'NewLand'
                                  | 'PentHouse'
                                  | 'Retirement'
                                  | 'SemiDetached'
                                  | 'Studio'
                                  | 'Terrace'
                                  | 'Townhouse'
                                  | 'VacantLand'
                                  | 'Villa'
                              )
                            | null
                        is_retirement: boolean | null
                    }[]
                }
            }
        }
    }
    findLatestRent: {
        parameters: {
            query?: {
                suburb_name?: string
                state_abbreviation?: 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'
                postcode?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        first_scrape_date: string | null
                        last_scrape_date: string | null
                        weekly_rent_aud: number | null
                        aud_per_bed: number | null
                        aud_per_land_m2: number | null
                        auction_time: string | null
                        longitude: number | null
                        latitude: number | null
                        inspection_time: string | null
                        land_m2: number | null
                        locality_table_id: number | null
                        street_address: string | null
                        bed_quantity: number | null
                        bath_quantity: number | null
                        car_quantity: number | null
                        home_type:
                            | (
                                  | 'Apartment'
                                  | 'ApartmentUnitFlat'
                                  | 'BlockOfUnits'
                                  | 'DevelopmentSite'
                                  | 'Duplex'
                                  | 'FreeStanding'
                                  | 'House'
                                  | 'Land'
                                  | 'NewApartments'
                                  | 'NewHomeDesigns'
                                  | 'NewHouseLand'
                                  | 'NewLand'
                                  | 'PentHouse'
                                  | 'Retirement'
                                  | 'SemiDetached'
                                  | 'Studio'
                                  | 'Terrace'
                                  | 'Townhouse'
                                  | 'VacantLand'
                                  | 'Villa'
                              )
                            | null
                        is_retirement: boolean | null
                    }[]
                }
            }
        }
    }
}
