/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/service-scrape/freemium/latestSale': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['findLatestSale']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/service-scrape/freemium/latestRent': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['findLatestRent']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    findLatestSale: {
        parameters: {
            query?: {
                postcode?: string
                state_abbreviation?: 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'
                suburb_name?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        aud_per_bed: number
                        aud_per_land_m2: number
                        /** Format: date-time */
                        first_scrape_date: string
                        higher_price_aud: number
                        home_table_id: number
                        /** Format: date-time */
                        last_scrape_date: string
                        auction_time: string | null
                        gps: string | null
                        home_feature_table_id: number
                        inspection_time: string | null
                        land_m2: number
                        locality_table_id: number
                        street_address: string
                        bath_quantity: number
                        bed_quantity: number
                        car_quantity: number
                        /** @enum {unknown} */
                        home_type:
                            | 'Apartment'
                            | 'ApartmentUnitFlat'
                            | 'BlockOfUnits'
                            | 'DevelopmentSite'
                            | 'Duplex'
                            | 'FreeStanding'
                            | 'House'
                            | 'Land'
                            | 'NewApartments'
                            | 'NewHomeDesigns'
                            | 'NewHouseLand'
                            | 'NewLand'
                            | 'PentHouse'
                            | 'Retirement'
                            | 'SemiDetached'
                            | 'Studio'
                            | 'Terrace'
                            | 'Townhouse'
                            | 'VacantLand'
                            | 'Villa'
                        is_retirement: boolean
                        boundary_coordinates: string
                        postcode: string
                        /** @enum {unknown} */
                        state_abbreviation:
                            | 'ACT'
                            | 'NSW'
                            | 'NT'
                            | 'QLD'
                            | 'SA'
                            | 'TAS'
                            | 'VIC'
                            | 'WA'
                        suburb_name: string
                    }[]
                }
            }
        }
    }
    findLatestRent: {
        parameters: {
            query?: {
                postcode?: string
                state_abbreviation?: 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'
                suburb_name?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': {
                        aud_per_bed: number
                        aud_per_land_m2: number
                        /** Format: date-time */
                        first_scrape_date: string
                        weekly_rent_aud: number
                        home_table_id: number
                        /** Format: date-time */
                        last_scrape_date: string
                        auction_time: string | null
                        gps: string | null
                        home_feature_table_id: number
                        inspection_time: string | null
                        land_m2: number
                        locality_table_id: number
                        street_address: string
                        bath_quantity: number
                        bed_quantity: number
                        car_quantity: number
                        /** @enum {unknown} */
                        home_type:
                            | 'Apartment'
                            | 'ApartmentUnitFlat'
                            | 'BlockOfUnits'
                            | 'DevelopmentSite'
                            | 'Duplex'
                            | 'FreeStanding'
                            | 'House'
                            | 'Land'
                            | 'NewApartments'
                            | 'NewHomeDesigns'
                            | 'NewHouseLand'
                            | 'NewLand'
                            | 'PentHouse'
                            | 'Retirement'
                            | 'SemiDetached'
                            | 'Studio'
                            | 'Terrace'
                            | 'Townhouse'
                            | 'VacantLand'
                            | 'Villa'
                        is_retirement: boolean
                        boundary_coordinates: string
                        postcode: string
                        /** @enum {unknown} */
                        state_abbreviation:
                            | 'ACT'
                            | 'NSW'
                            | 'NT'
                            | 'QLD'
                            | 'SA'
                            | 'TAS'
                            | 'VIC'
                            | 'WA'
                        suburb_name: string
                    }[]
                }
            }
        }
    }
}
