// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { homeTypeEnum, type default as HomeTypeEnum } from './HomeTypeEnum'
import { z } from 'zod'

/** Identifier type for public.home_feature_table */
export type HomeFeatureTableId = number & { __brand: 'public.home_feature_table' }

/** Represents the table public.home_feature_table */
export default interface HomeFeatureTable {
    id: HomeFeatureTableId

    bed_quantity: number

    bath_quantity: number

    car_quantity: number

    home_type: HomeTypeEnum

    is_retirement: boolean
}

/** Represents the initializer for the table public.home_feature_table */
export interface HomeFeatureTableInitializer {
    id?: HomeFeatureTableId

    bed_quantity: number

    bath_quantity: number

    car_quantity: number

    home_type: HomeTypeEnum

    is_retirement: boolean
}

/** Represents the mutator for the table public.home_feature_table */
export interface HomeFeatureTableMutator {
    id?: HomeFeatureTableId

    bed_quantity?: number

    bath_quantity?: number

    car_quantity?: number

    home_type?: HomeTypeEnum

    is_retirement?: boolean
}

export const homeFeatureTableId = z.number() as unknown as z.Schema<HomeFeatureTableId>

export const homeFeatureTable = z.object({
    id: homeFeatureTableId,
    bed_quantity: z.number(),
    bath_quantity: z.number(),
    car_quantity: z.number(),
    home_type: homeTypeEnum,
    is_retirement: z.boolean(),
}) as unknown as z.Schema<HomeFeatureTable>

export const homeFeatureTableInitializer = z.object({
    id: homeFeatureTableId.optional(),
    bed_quantity: z.number(),
    bath_quantity: z.number(),
    car_quantity: z.number(),
    home_type: homeTypeEnum,
    is_retirement: z.boolean(),
}) as unknown as z.Schema<HomeFeatureTableInitializer>

export const homeFeatureTableMutator = z.object({
    id: homeFeatureTableId.optional(),
    bed_quantity: z.number().optional(),
    bath_quantity: z.number().optional(),
    car_quantity: z.number().optional(),
    home_type: homeTypeEnum.optional(),
    is_retirement: z.boolean().optional(),
}) as unknown as z.Schema<HomeFeatureTableMutator>
