// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod'

/** Represents the enum public.home_type_enum */
type HomeTypeEnum =
    | 'Apartment'
    | 'ApartmentUnitFlat'
    | 'BlockOfUnits'
    | 'DevelopmentSite'
    | 'Duplex'
    | 'FreeStanding'
    | 'House'
    | 'Land'
    | 'NewApartments'
    | 'NewHomeDesigns'
    | 'NewHouseLand'
    | 'NewLand'
    | 'PentHouse'
    | 'Retirement'
    | 'SemiDetached'
    | 'Studio'
    | 'Terrace'
    | 'Townhouse'
    | 'VacantLand'
    | 'Villa'

export default HomeTypeEnum

/** Zod schema for home_type_enum */
export const homeTypeEnum = z.enum([
    'Apartment',
    'ApartmentUnitFlat',
    'BlockOfUnits',
    'DevelopmentSite',
    'Duplex',
    'FreeStanding',
    'House',
    'Land',
    'NewApartments',
    'NewHomeDesigns',
    'NewHouseLand',
    'NewLand',
    'PentHouse',
    'Retirement',
    'SemiDetached',
    'Studio',
    'Terrace',
    'Townhouse',
    'VacantLand',
    'Villa',
])
