// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { localityTableId, type LocalityTableId } from './LocalityTable'
import { homeFeatureTableId, type HomeFeatureTableId } from './HomeFeatureTable'
import { z } from 'zod'

/** Identifier type for public.home_table */
export type HomeTableId = number & { __brand: 'public.home_table' }

/** Represents the table public.home_table */
export default interface HomeTable {
    id: HomeTableId

    locality_table_id: LocalityTableId

    home_feature_table_id: HomeFeatureTableId

    street_address: string

    gps: string

    land_m2: number

    inspection_time: Date

    auction_time: Date
}

/** Represents the initializer for the table public.home_table */
export interface HomeTableInitializer {
    id?: HomeTableId

    locality_table_id: LocalityTableId

    home_feature_table_id: HomeFeatureTableId

    street_address: string

    gps: string

    land_m2: number

    inspection_time: Date

    auction_time: Date
}

/** Represents the mutator for the table public.home_table */
export interface HomeTableMutator {
    id?: HomeTableId

    locality_table_id?: LocalityTableId

    home_feature_table_id?: HomeFeatureTableId

    street_address?: string

    gps?: string

    land_m2?: number

    inspection_time?: Date

    auction_time?: Date
}

export const homeTableId = z.number().transform((value) => value as HomeTableId)

export const homeTable = z.object({
    id: homeTableId,
    locality_table_id: localityTableId,
    home_feature_table_id: homeFeatureTableId,
    street_address: z.string(),
    gps: z.string(),
    land_m2: z.number(),
    inspection_time: z.date(),
    auction_time: z.date(),
})

export const homeTableInitializer = z.object({
    id: homeTableId.optional(),
    locality_table_id: localityTableId,
    home_feature_table_id: homeFeatureTableId,
    street_address: z.string(),
    gps: z.string(),
    land_m2: z.number(),
    inspection_time: z.date(),
    auction_time: z.date(),
})

export const homeTableMutator = z.object({
    id: homeTableId.optional(),
    locality_table_id: localityTableId.optional(),
    home_feature_table_id: homeFeatureTableId.optional(),
    street_address: z.string().optional(),
    gps: z.string().optional(),
    land_m2: z.number().optional(),
    inspection_time: z.date().optional(),
    auction_time: z.date().optional(),
})
