// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { homeTypeEnum, type default as HomeTypeEnum } from './HomeTypeEnum'
import { z } from 'zod'

/** Represents the materializedView public.latest_sale_mv */
export default interface LatestSaleMv {
    first_scrape_date: Date | null

    last_scrape_date: Date | null

    higher_price_aud: number | null

    aud_per_bed: number | null

    aud_per_land_m2: number | null

    auction_time: Date | null

    longitude: number | null

    latitude: number | null

    inspection_time: Date | null

    land_m2: number | null

    locality_table_id: number | null

    street_address: string | null

    bed_quantity: number | null

    bath_quantity: number | null

    car_quantity: number | null

    home_type: HomeTypeEnum | null

    is_retirement: boolean | null
}

export const latestSaleMv = z.object({
    first_scrape_date: z.date().nullable(),
    last_scrape_date: z.date().nullable(),
    higher_price_aud: z.number().nullable(),
    aud_per_bed: z.number().nullable(),
    aud_per_land_m2: z.number().nullable(),
    auction_time: z.date().nullable(),
    longitude: z.number().nullable(),
    latitude: z.number().nullable(),
    inspection_time: z.date().nullable(),
    land_m2: z.number().nullable(),
    locality_table_id: z.number().nullable(),
    street_address: z.string().nullable(),
    bed_quantity: z.number().nullable(),
    bath_quantity: z.number().nullable(),
    car_quantity: z.number().nullable(),
    home_type: homeTypeEnum.nullable(),
    is_retirement: z.boolean().nullable(),
})
