// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import {
    stateAbbreviationEnum,
    type default as StateAbbreviationEnum,
} from './StateAbbreviationEnum'
import { z } from 'zod'

/** Identifier type for public.locality_table */
export type LocalityTableId = number & { __brand: 'public.locality_table' }

/** Represents the table public.locality_table */
export default interface LocalityTable {
    id: LocalityTableId

    suburb_name: string

    postcode: string

    state_abbreviation: StateAbbreviationEnum

    boundary_coordinates: string
}

/** Represents the initializer for the table public.locality_table */
export interface LocalityTableInitializer {
    id?: LocalityTableId

    suburb_name: string

    postcode: string

    state_abbreviation: StateAbbreviationEnum

    boundary_coordinates: string
}

/** Represents the mutator for the table public.locality_table */
export interface LocalityTableMutator {
    id?: LocalityTableId

    suburb_name?: string

    postcode?: string

    state_abbreviation?: StateAbbreviationEnum

    boundary_coordinates?: string
}

export const localityTableId = z.number() as unknown as z.Schema<LocalityTableId>

export const localityTable = z.object({
    id: localityTableId,
    suburb_name: z.string(),
    postcode: z.string(),
    state_abbreviation: stateAbbreviationEnum,
    boundary_coordinates: z.string(),
}) as unknown as z.Schema<LocalityTable>

export const localityTableInitializer = z.object({
    id: localityTableId.optional(),
    suburb_name: z.string(),
    postcode: z.string(),
    state_abbreviation: stateAbbreviationEnum,
    boundary_coordinates: z.string(),
}) as unknown as z.Schema<LocalityTableInitializer>

export const localityTableMutator = z.object({
    id: localityTableId.optional(),
    suburb_name: z.string().optional(),
    postcode: z.string().optional(),
    state_abbreviation: stateAbbreviationEnum.optional(),
    boundary_coordinates: z.string().optional(),
}) as unknown as z.Schema<LocalityTableMutator>
