// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { homeTableId, type HomeTableId } from './HomeTable'
import { z } from 'zod'

/** Identifier type for public.rent_price_table */
export type RentPriceTableId = number & { __brand: 'public.rent_price_table' }

/** Represents the table public.rent_price_table */
export default interface RentPriceTable {
    id: RentPriceTableId

    home_table_id: HomeTableId

    first_scrape_date: Date

    last_scrape_date: Date

    weekly_rent_aud: number

    aud_per_bed: number

    aud_per_land_m2: number
}

/** Represents the initializer for the table public.rent_price_table */
export interface RentPriceTableInitializer {
    home_table_id: HomeTableId

    /** Default value: now() */
    first_scrape_date?: Date

    /** Default value: now() */
    last_scrape_date?: Date

    weekly_rent_aud: number

    aud_per_bed: number

    aud_per_land_m2: number
}

/** Represents the mutator for the table public.rent_price_table */
export interface RentPriceTableMutator {
    home_table_id?: HomeTableId

    first_scrape_date?: Date

    last_scrape_date?: Date

    weekly_rent_aud?: number

    aud_per_bed?: number

    aud_per_land_m2?: number
}

export const rentPriceTableId = z.number().transform((value) => value as RentPriceTableId)

export const rentPriceTable = z.object({
    id: rentPriceTableId,
    home_table_id: homeTableId,
    first_scrape_date: z.date(),
    last_scrape_date: z.date(),
    weekly_rent_aud: z.number(),
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
})

export const rentPriceTableInitializer = z.object({
    id: rentPriceTableId.optional(),
    home_table_id: homeTableId,
    first_scrape_date: z.date().optional(),
    last_scrape_date: z.date().optional(),
    weekly_rent_aud: z.number(),
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
})

export const rentPriceTableMutator = z.object({
    id: rentPriceTableId.optional(),
    home_table_id: homeTableId.optional(),
    first_scrape_date: z.date().optional(),
    last_scrape_date: z.date().optional(),
    weekly_rent_aud: z.number().optional(),
    aud_per_bed: z.number().optional(),
    aud_per_land_m2: z.number().optional(),
})
