// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { homeTableId, type HomeTableId } from './HomeTable'
import { z } from 'zod'

/** Identifier type for public.sale_price_table */
export type SalePriceTableId = number & { __brand: 'public.sale_price_table' }

/** Represents the table public.sale_price_table */
export default interface SalePriceTable {
    id: SalePriceTableId

    home_table_id: HomeTableId

    first_scrape_date: Date

    last_scrape_date: Date

    higher_price_aud: number

    aud_per_bed: number

    aud_per_land_m2: number
}

/** Represents the initializer for the table public.sale_price_table */
export interface SalePriceTableInitializer {
    home_table_id: HomeTableId

    /** Default value: now() */
    first_scrape_date?: Date

    /** Default value: now() */
    last_scrape_date?: Date

    higher_price_aud: number

    aud_per_bed: number

    aud_per_land_m2: number
}

/** Represents the mutator for the table public.sale_price_table */
export interface SalePriceTableMutator {
    home_table_id?: HomeTableId

    first_scrape_date?: Date

    last_scrape_date?: Date

    higher_price_aud?: number

    aud_per_bed?: number

    aud_per_land_m2?: number
}

export const salePriceTableId = z.number().transform((value) => value as SalePriceTableId)

export const salePriceTable = z.object({
    id: salePriceTableId,
    home_table_id: homeTableId,
    first_scrape_date: z.date(),
    last_scrape_date: z.date(),
    higher_price_aud: z.number(),
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
})

export const salePriceTableInitializer = z.object({
    id: salePriceTableId.optional(),
    home_table_id: homeTableId,
    first_scrape_date: z.date().optional(),
    last_scrape_date: z.date().optional(),
    higher_price_aud: z.number(),
    aud_per_bed: z.number(),
    aud_per_land_m2: z.number(),
})

export const salePriceTableMutator = z.object({
    id: salePriceTableId.optional(),
    home_table_id: homeTableId.optional(),
    first_scrape_date: z.date().optional(),
    last_scrape_date: z.date().optional(),
    higher_price_aud: z.number().optional(),
    aud_per_bed: z.number().optional(),
    aud_per_land_m2: z.number().optional(),
})
