// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { schoolFeatureTableId, type SchoolFeatureTableId } from './SchoolFeatureTable'
import { localityTableId, type LocalityTableId } from './LocalityTable'
import {
    stateAbbreviationEnum,
    type default as StateAbbreviationEnum,
} from './StateAbbreviationEnum'
import { z } from 'zod'

/** Represents the view public.school_view */
export default interface SchoolView {
    acara_id: number

    name: string

    url: string

    gps: string

    school_feature_table_id: SchoolFeatureTableId

    primary: boolean

    secondary: boolean

    government_sector: boolean

    independent: boolean

    special_needs: boolean

    locality_table_id: LocalityTableId

    suburb_name: string

    state_abbreviation: StateAbbreviationEnum

    postcode: string

    boundary_coordinates: string
}

export const schoolView = z.object({
    acara_id: z.number(),
    name: z.string(),
    url: z.string(),
    gps: z.string(),
    school_feature_table_id: schoolFeatureTableId,
    primary: z.boolean(),
    secondary: z.boolean(),
    government_sector: z.boolean(),
    independent: z.boolean(),
    special_needs: z.boolean(),
    locality_table_id: localityTableId,
    suburb_name: z.string(),
    state_abbreviation: stateAbbreviationEnum,
    postcode: z.string(),
    boundary_coordinates: z.string(),
})
