// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod'

/** Identifier type for public.school_feature_table */
export type SchoolFeatureTableId = number & { __brand: 'public.school_feature_table' }

/** Represents the table public.school_feature_table */
export default interface SchoolFeatureTable {
    id: SchoolFeatureTableId

    primary: boolean

    secondary: boolean

    government_sector: boolean

    independent: boolean

    special_needs: boolean
}

/** Represents the initializer for the table public.school_feature_table */
export interface SchoolFeatureTableInitializer {
    primary: boolean

    secondary: boolean

    government_sector: boolean

    independent: boolean

    special_needs: boolean
}

/** Represents the mutator for the table public.school_feature_table */
export interface SchoolFeatureTableMutator {
    primary?: boolean

    secondary?: boolean

    government_sector?: boolean

    independent?: boolean

    special_needs?: boolean
}

export const schoolFeatureTableId = z.number().transform((value) => value as SchoolFeatureTableId)

export const schoolFeatureTable = z.object({
    id: schoolFeatureTableId,
    primary: z.boolean(),
    secondary: z.boolean(),
    government_sector: z.boolean(),
    independent: z.boolean(),
    special_needs: z.boolean(),
})

export const schoolFeatureTableInitializer = z.object({
    id: schoolFeatureTableId.optional(),
    primary: z.boolean(),
    secondary: z.boolean(),
    government_sector: z.boolean(),
    independent: z.boolean(),
    special_needs: z.boolean(),
})

export const schoolFeatureTableMutator = z.object({
    id: schoolFeatureTableId.optional(),
    primary: z.boolean().optional(),
    secondary: z.boolean().optional(),
    government_sector: z.boolean().optional(),
    independent: z.boolean().optional(),
    special_needs: z.boolean().optional(),
})
