// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { localityTableId, type LocalityTableId } from './LocalityTable'
import { schoolFeatureTableId, type SchoolFeatureTableId } from './SchoolFeatureTable'
import { z } from 'zod'

/** Identifier type for public.school_table */
export type SchoolTableId = number & { __brand: 'public.school_table' }

/** Represents the table public.school_table */
export default interface SchoolTable {
    id: SchoolTableId

    locality_table_id: LocalityTableId

    school_feature_table_id: SchoolFeatureTableId

    acara_id: number

    name: string

    url: string

    gps: string
}

/** Represents the initializer for the table public.school_table */
export interface SchoolTableInitializer {
    locality_table_id: LocalityTableId

    school_feature_table_id: SchoolFeatureTableId

    acara_id: number

    name: string

    url: string

    gps: string
}

/** Represents the mutator for the table public.school_table */
export interface SchoolTableMutator {
    locality_table_id?: LocalityTableId

    school_feature_table_id?: SchoolFeatureTableId

    acara_id?: number

    name?: string

    url?: string

    gps?: string
}

export const schoolTableId = z.number().transform((value) => value as SchoolTableId)

export const schoolTable = z.object({
    id: schoolTableId,
    locality_table_id: localityTableId,
    school_feature_table_id: schoolFeatureTableId,
    acara_id: z.number(),
    name: z.string(),
    url: z.string(),
    gps: z.string(),
})

export const schoolTableInitializer = z.object({
    id: schoolTableId.optional(),
    locality_table_id: localityTableId,
    school_feature_table_id: schoolFeatureTableId,
    acara_id: z.number(),
    name: z.string(),
    url: z.string(),
    gps: z.string(),
})

export const schoolTableMutator = z.object({
    id: schoolTableId.optional(),
    locality_table_id: localityTableId.optional(),
    school_feature_table_id: schoolFeatureTableId.optional(),
    acara_id: z.number().optional(),
    name: z.string().optional(),
    url: z.string().optional(),
    gps: z.string().optional(),
})
