// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod'

/** Represents the enum public.state_abbreviation_enum */
enum StateAbbreviationEnum {
    ACT = 'ACT',
    NSW = 'NSW',
    NT = 'NT',
    QLD = 'QLD',
    SA = 'SA',
    TAS = 'TAS',
    VIC = 'VIC',
    WA = 'WA',
}

export default StateAbbreviationEnum

/** Zod schema for state_abbreviation_enum */
export const stateAbbreviationEnum = z.enum(StateAbbreviationEnum)
