// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod'

/** Represents the enum public.state_abbreviation_enum */
type StateAbbreviationEnum = 'ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA'

export default StateAbbreviationEnum

/** Zod schema for state_abbreviation_enum */
export const stateAbbreviationEnum = z.enum(['ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA'])
