--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: home_type_enum; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.home_type_enum AS ENUM (
    'ApartmentUnitFlat',
    'House',
    'Townhouse',
    'BlockOfUnits'
);


ALTER TYPE public.home_type_enum OWNER TO "user";

--
-- Name: state_abbreviation_enum; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.state_abbreviation_enum AS ENUM (
    'ACT',
    'NSW',
    'NT',
    'QLD',
    'SA',
    'TAS',
    'VIC',
    'WA'
);


ALTER TYPE public.state_abbreviation_enum OWNER TO "user";

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: common_features_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.common_features_table (
    id integer NOT NULL,
    bed_quantity integer NOT NULL,
    bath_quantity integer NOT NULL,
    car_quantity integer NOT NULL,
    home_type public.home_type_enum NOT NULL,
    is_retirement boolean NOT NULL,
    CONSTRAINT common_features_table_bath_quantity_check CHECK (((bath_quantity >= 0) AND (bath_quantity <= 5))),
    CONSTRAINT common_features_table_bed_quantity_check CHECK (((bed_quantity >= 0) AND (bed_quantity <= 5))),
    CONSTRAINT common_features_table_car_quantity_check CHECK (((car_quantity >= 0) AND (car_quantity <= 5)))
);


ALTER TABLE public.common_features_table OWNER TO "user";

--
-- Name: common_features_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.common_features_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_features_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO "user";

--
-- Name: home_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.home_table (
    id integer NOT NULL,
    localities_table_id integer,
    common_features_table_id integer,
    street_address text NOT NULL,
    gps public.geometry(Point) NOT NULL,
    land_m2 integer,
    inspection_time time without time zone,
    auction_time time without time zone,
    CONSTRAINT home_table_street_address_check CHECK ((length(street_address) < 64))
);


ALTER TABLE public.home_table OWNER TO "user";

--
-- Name: home_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.home_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.home_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: localities_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.localities_table (
    id integer NOT NULL,
    suburb_name text NOT NULL,
    postcode text NOT NULL,
    state_abbreviation public.state_abbreviation_enum NOT NULL,
    CONSTRAINT localities_table_postcode_check CHECK ((length(postcode) = 4)),
    CONSTRAINT localities_table_suburb_name_check CHECK ((length(suburb_name) < 64))
);


ALTER TABLE public.localities_table OWNER TO "user";

--
-- Name: localities_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.localities_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.localities_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rent_price_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.rent_price_table (
    id integer NOT NULL,
    home_table_id integer,
    first_scrape_date date DEFAULT now() NOT NULL,
    last_scrape_date date DEFAULT now() NOT NULL,
    weekly_rent_aud real NOT NULL,
    aud_per_bed real,
    aud_per_land_m2 real
);


ALTER TABLE public.rent_price_table OWNER TO "user";

--
-- Name: rent_price_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.rent_price_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_price_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_price_table; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.sale_price_table (
    id integer NOT NULL,
    home_table_id integer,
    first_scrape_date date DEFAULT now() NOT NULL,
    last_scrape_date date DEFAULT now() NOT NULL,
    higher_price_aud integer NOT NULL,
    aud_per_bed real,
    aud_per_land_m2 real
);


ALTER TABLE public.sale_price_table OWNER TO "user";

--
-- Name: sale_price_table_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.sale_price_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_price_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_features_table common_features_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.common_features_table
    ADD CONSTRAINT common_features_table_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: home_table home_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_pkey PRIMARY KEY (id);


--
-- Name: localities_table localities_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.localities_table
    ADD CONSTRAINT localities_table_pkey PRIMARY KEY (id);


--
-- Name: rent_price_table rent_price_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.rent_price_table
    ADD CONSTRAINT rent_price_table_pkey PRIMARY KEY (id);


--
-- Name: sale_price_table sale_price_table_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sale_price_table
    ADD CONSTRAINT sale_price_table_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: home_table home_table_common_features_table_id_common_features_table_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_common_features_table_id_common_features_table_id_fk FOREIGN KEY (common_features_table_id) REFERENCES public.common_features_table(id);


--
-- Name: home_table home_table_localities_table_id_localities_table_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.home_table
    ADD CONSTRAINT home_table_localities_table_id_localities_table_id_fk FOREIGN KEY (localities_table_id) REFERENCES public.localities_table(id);


--
-- Name: rent_price_table rent_price_table_home_table_id_home_table_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.rent_price_table
    ADD CONSTRAINT rent_price_table_home_table_id_home_table_id_fk FOREIGN KEY (home_table_id) REFERENCES public.home_table(id);


--
-- Name: sale_price_table sale_price_table_home_table_id_home_table_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.sale_price_table
    ADD CONSTRAINT sale_price_table_home_table_id_home_table_id_fk FOREIGN KEY (home_table_id) REFERENCES public.home_table(id);


--
-- PostgreSQL database dump complete
--

