CREATE TYPE "public"."home_type_enum" AS ENUM('ApartmentUnitFlat', 'House', 'Townhouse', 'BlockOfUnits');--> statement-breakpoint
CREATE TYPE "public"."state_abbreviation_enum" AS ENUM('ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA');--> statement-breakpoint
CREATE TABLE "common_features_table" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "common_features_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"bed_quantity" smallint NOT NULL,
	"bath_quantity" smallint NOT NULL,
	"car_quantity" smallint NOT NULL,
	"home_type" "home_type_enum" NOT NULL,
	"is_retirement" boolean NOT NULL,
	CONSTRAINT "common_features_table_bed_quantity_check" CHECK ("common_features_table"."bed_quantity" >= 0 AND "common_features_table"."bed_quantity" <= 10),
	CONSTRAINT "common_features_table_bath_quantity_check" CHECK ("common_features_table"."bath_quantity" >= 0  AND "common_features_table"."bath_quantity" <= 5),
	CONSTRAINT "common_features_table_car_quantity_check" CHECK ("common_features_table"."car_quantity" >= 0  AND "common_features_table"."car_quantity" <= 20)
);
--> statement-breakpoint
CREATE TABLE "home_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "home_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"localities_table_id" smallint,
	"common_features_table_id" smallint,
	"street_address" text NOT NULL,
	"gps" geometry(point) NOT NULL,
	"land_m2" smallint,
	"inspection_time" time,
	"auction_time" time,
	CONSTRAINT "home_table_street_address_check" CHECK (LENGTH("home_table"."street_address") < 64)
);
--> statement-breakpoint
CREATE TABLE "localities_table" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "localities_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"suburb_name" text NOT NULL,
	"postcode" text NOT NULL,
	"state_abbreviation" "state_abbreviation_enum" NOT NULL,
	CONSTRAINT "localities_table_suburb_name_check" CHECK (LENGTH("localities_table"."suburb_name") < 64),
	CONSTRAINT "localities_table_postcode_check" CHECK (LENGTH("localities_table"."postcode") = 4)
);
--> statement-breakpoint
CREATE TABLE "rent_price_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rent_price_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"home_table_id" integer,
	"first_scrape_date" date DEFAULT now() NOT NULL,
	"last_scrape_date" date DEFAULT now() NOT NULL,
	"weekly_rent_aud" smallint NOT NULL,
	"aud_per_bed" smallint
);
--> statement-breakpoint
CREATE TABLE "sale_price_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sale_price_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"home_table_id" integer,
	"first_scrape_date" date DEFAULT now() NOT NULL,
	"last_scrape_date" date DEFAULT now() NOT NULL,
	"higher_price_aud" integer NOT NULL,
	"aud_per_bed" integer,
	"aud_per_land_m2" integer
);
--> statement-breakpoint
ALTER TABLE "home_table" ADD CONSTRAINT "home_table_localities_table_id_localities_table_id_fk" FOREIGN KEY ("localities_table_id") REFERENCES "public"."localities_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "home_table" ADD CONSTRAINT "home_table_common_features_table_id_common_features_table_id_fk" FOREIGN KEY ("common_features_table_id") REFERENCES "public"."common_features_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rent_price_table" ADD CONSTRAINT "rent_price_table_home_table_id_home_table_id_fk" FOREIGN KEY ("home_table_id") REFERENCES "public"."home_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sale_price_table" ADD CONSTRAINT "sale_price_table_home_table_id_home_table_id_fk" FOREIGN KEY ("home_table_id") REFERENCES "public"."home_table"("id") ON DELETE no action ON UPDATE no action;
