AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: service-scrape - A scraper for real estate data

Globals:
  Function:
    Runtime: dotnet8
    Architectures:
      - arm64 # Faster execution and cheaper
    LoggingConfig: NoLogging # Expensive cloudwatch
    ReservedConcurrentExecutions: 1 # Smallest default
    Timeout: 1 # Smallest default
    MemorySize: 1769 # Also allocates 1vCPU
    Handler: Program::Program.LambdaFunction::LambdaFunctionHandler

Resources:
  BatchTrigger:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60 # Jobs may come in various sizes
      MemorySize: 256 # Limit CPU to throttle scraping
      CodeUri: ./function-batchTrigger/src/
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * Sat) # 3am Sat UTC => 1pm Sat AEST
            Name: BatchTriggerEvent
      Environment:
        Variables:
          BATCHSCRAPESUBURBSQUEUE_QUEUE_NAME: !GetAtt BatchScrapeSuburbsQueue.QueueName
          BATCHSCRAPESUBURBSQUEUE_QUEUE_ARN: !GetAtt BatchScrapeSuburbsQueue.Arn
          BATCHSCRAPESUBURBSQUEUE_QUEUE_URL: !Ref BatchScrapeSuburbsQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BatchScrapeSuburbsQueue.QueueName
  BatchScrapeSuburbsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: BatchScrapeSuburbsQueue
      MessageRetentionPeriod: 432000 # Retain for 5 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BatchScrapeSuburbsDLQ.Arn
        maxReceiveCount: 3 # Retry 3 times
  BatchScrapeSuburbsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: BatchScrapeSuburbsQueue
      MessageRetentionPeriod: 1209600 # Retain for 14 days
  BatchScrapeSuburbs:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900 # Jobs may come in various sizes
      MemorySize: 256 # Limit CPU to throttle scraping
      CodeUri: ./function-batchScrapeSuburbs/src/
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt BatchScrapeSuburbsQueue.Arn
            BatchSize: 10
            Enabled: false
            ScalingConfig:
              MaximumConcurrency: 1
  ReadOLTP:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 10 # Prevent database overload
      Timeout: 3
      CodeUri: ./function-readOLTP/src/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: get # Cacheable

Outputs:
  EnspointUrl:
    Description: Prod API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod