FROM --platform=linux/arm64 node:24.12.0-trixie-slim

WORKDIR /app

# Clean package manager
RUN apt clean &&\
    rm -R /var/lib/apt/lists/* &&\
    echo 'Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;' >  /etc/apt/apt.conf.d/99fixbadproxy &&\
    apt update &&\
    # Lock playwright version
    npm i playwright@1.57.0 &&\
    # Install headless chrome for playwright
    npx playwright@1.57.0 install --with-deps --only-shell chromium

# Better debugging and remove `punycode` warning
ENV NODE_OPTIONS="--enable-source-maps --no-deprecation"

# Copy bundled script and sourcemap
COPY ./dist ./package.json /app
CMD ["node", "/app/index.js"]
