{
 "title": "stack-service_scrape_pipeline",
 "time": { "from": "2025-09-26T16:00:00.000Z", "to": "2025-09-26T18:15:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "heatmap_interval",
    "query": "1s,2s,5s,10s,20s,30s,1m,2m,5m,10m,15m,20m"
   },
   {
    "name": "log_level",
    "query": "fatal,error,warn,info,debug,trace"
   },
   {
    "name": "service_name",
    "label": "service_name",
    "query": "function-scrape_locality_trigger,function-scrape_locality"
   }
  ]
 },
 "panels": [
  { "title": "$service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_name" },
  {
   "title": "faas_duration histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"NewHomie\", service_name=\"$service_name\"} | detected_level =~ `info` | faas_duration > 0"
    }
   ]
  },
  {
   "title": "faas_duration",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"NewHomie\", service_name=\"$service_name\"} | detected_level =~ `info` | faas_duration > 0"
    }
   ]
  },
  {
   "title": "faas_duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"NewHomie\", service_name=\"$service_name\"} | detected_level =~ `info` | faas_duration > 0"
    }
   ]
  },
  {
   "title": "detected_level heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "Source",
     "type": "resample",
     "upsampler": "fillna",
     "window": "$heatmap_interval"
    }
   ]
  },
  {
   "title": "code_function_name heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "downsampler": "sum",
     "expression": "Source",
     "type": "resample",
     "upsampler": "fillna",
     "window": "$heatmap_interval"
    }
   ]
  },
  {
   "title": "detected_level exception logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"NewHomie\", service_name=\"$service_name\"} | detected_level =~ `${log_level}`"
    }
   ]
  }
 ]
}